# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-5.17

packages:
  - '.'

extra-deps:
  - semigroups-0.18
  - pretty-1.1.3.4
  - data-fix-0.0.3
